Gw 49
varchugov/hh-gowork pull request #39
Opened 2021-05-27 21:17 UTC by PavelDubrov

Задача [GW-49](https://trello.com/c/63tK3aVj/49-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%8C-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BE%D0%B2-%D0%B2-%D0%B1%D0%B4) в `trello.com`

### Что было сделано в задаче
Был добавлен ресурс AnswerResource, с помощью которого можно записать ответ юзера в базу, и получать объяснение на его ответ.

### Как протестировать

поднимаем проект в докере
`docker-compose up -d back`

логинимся
`curl -i -X POST http://127.0.0.1:8080/login -d 'email=test@example.com&password=test'`

получаем куку
( пример куки:  gw_session=918ec829-2fa6-4978-8134-06a4b8a2e0a0 )

делаем запрос с полученной кукой
`curl -i -X POST localhost:8080/session/"918ec829-2fa6-4978-8134-06a4b8a2e0a0"/answer/'{\"tree\":\"green\"}'`

проверяем, записалось ли в БД
`sudo docker-compose exec postgres psql -U hh -c "SELECT * FROM users_answers"`

Не разобрался, как сделать так, чтобы json нормально записывался в БД
При проверке БД предыдущим запросом, мы увидим, что в БД в столбец с ответом записалось "tree".

### Скриншоты, если были изменения в верстке

## Чеклист для проверки

- [ ] Ветка называется `GW-[номер задачи из трелло]`. Для задачи https://trello.com/c/cjbG0nCi/44-test ветка будет называться `GW-44`
- [ ] Задача в трелло стоит в колонке review
- [ ] Этот PR открыт только для одной задачи
- [ ] Все коммиты пишутся как `GW-[номер задачи из трелло] суть изменений`, например: `GW-44 add test task`
- [ ] Нет лишних коммитов, типа `fix`, `tmp`
- [ ] Базовая ветка установлена правильно, в PR нет чужих коммитов и мержей

2021-05-28 14:43 UTC, SuhoyVasya requested changes

2021-05-28 14:43 UTC, SuhoyVasya commented on back/src/main/java/ru/gowork/config/ProdConfig.java
> +import ru.gowork.service.StudentsService;
чего ты их вдруг решил пересортировать?)

2021-05-28 14:43 UTC, SuhoyVasya commented on back/src/main/java/ru/gowork/service/AnswerService.java
> +        User user = userOptional.get();
Это не хороший способ юзать  Optional
для преобразований есть map, ifPresentOrElse и прочее

2021-05-30 10:45 UTC, PavelDubrov commented on back/src/main/java/ru/gowork/config/ProdConfig.java
> +import ru.gowork.service.StudentsService;
Вернул все как было)

2021-05-30 10:47 UTC, PavelDubrov commented on back/src/main/java/ru/gowork/service/AnswerService.java
> +        User user = userOptional.get();
Поменял
Спасибо за помощь)

2021-05-31 17:20 UTC, SuhoyVasya approved these changes

2021-05-31 17:21 UTC, SuhoyVasya commented on back/src/main/java/ru/gowork/resource/ParagraphResource.java
> -    @Path("/chapters/{chapter_id}/paragraphs/{paragraph_id}/steps/{step_id}/check_answer")
Этото ресурс точно не нужен?

2021-05-31 17:25 UTC, PavelDubrov commented on back/src/main/java/ru/gowork/resource/ParagraphResource.java
> -    @Path("/chapters/{chapter_id}/paragraphs/{paragraph_id}/steps/{step_id}/check_answer")
да, все так и задумано )

2021-05-31 18:51 UTC, merged