[GW-83] Limit workflow and jobs run concurrency of CD
varchugov/hh-gowork pull request #60
Opened 2021-06-15 21:16 UTC by devlsay

Задача [GW-###](link) в `trello.com`

### Что было сделано в задаче

Настроен последовательный запуск Рабочих процессов [workflow] GoWork CI/CD и некоторых Заданий [job], связанных с CD 

### Как протестировать

Принять одновременно несколько ПР, и запустить установку Миграций [Migration] на удаленном сервере

## Чеклист для проверки

- [ ] Ветка называется `GW-[номер задачи из трелло]`. Для задачи https://trello.com/c/cjbG0nCi/44-test ветка будет называться `GW-44`
- [ ] Задача в трелло стоит в колонке review
- [ ] Этот PR открыт только для одной задачи
- [ ] Все коммиты пишутся как `GW-[номер задачи из трелло] суть изменений`, например: `GW-44 add test task`
- [ ] Нет лишних коммитов, типа `fix`, `tmp`
- [ ] Базовая ветка установлена правильно, в PR нет чужих коммитов и мержей

2021-06-16 13:40 UTC, nikitakalyanov approved these changes

2021-06-16 23:17 UTC, samnix-p requested changes

2021-06-17 10:09 UTC, devlsay commented on .github/workflows/gowork-cicd.yml
> +            git clean -f
Спасибо за то, что заметил :)
Готово*

2021-06-17 11:05 UTC, samnix-p approved these changes

2021-06-17 11:06 UTC, merged